version: '3'
services:
#  jenkins:
#     container_name: jenkinsspringboot
#     image: jenkinsci/blueocean
#     ports:
#       - "8080:8080"
#     volumes:
#       - "$PWD/jenkins_home:/var/jenkins_home"
    #  - "$PWD# /var/run/docker.socker/var/run/docker.sock"
#      network:
#        - n# et
  db_pos:
    container_name: dbs
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=pos
      - MYSQL_USER=gicelli
      - MYSQL_PASSWORDpassword 
    volumes:
      - "$PWD/db_data :/var/lib/mysql"
    networks:
      - net
  spring:
    container_name: spring
    image: spring
    ports:
      - "8087:8080"
    expose:
      - "8080" 
    build: ./
    depends_on:
      - db_pos
    networks:
     - net


        #ipv6_address: 192.168.1.99
networks:
  net: 
